version: 2
project_name: ezazssh
builds:
  - id: "ezazssh"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0  # Disable CGO for static compilation
    flags:
      - -trimpath
    ldflags:
      - -s -w  # Strip debug info to reduce size
      - -extldflags "-static" 
upx:
  - enabled: true
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    builds:
      - ezazssh
